version: "2.1"

services:
  openssh-server:
    image: tmux-pair-service
    container_name: tmux-pair-service
    build:
      context: ./tmux-server
      dockerfile: Dockerfile
    hostname: openssh-server #optional
    entrypoint: /init
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Europe/London
      #- PUBLIC_KEY=yourpublickey #optional
      #- PUBLIC_KEY_FILE=/path/to/file #optional
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      #- PUBLIC_KEY_URL=https://github.com/username.keys #optional
      #- SUDO_ACCESS=false #optional
      - USER_NAME=tmux #optional
      - USER_PASSWORD=f23442f34564572a #optional
      - PASSWORD_ACCESS=true #optional
      #- USER_PASSWORD_FILE=/path/to/file #optional
    #volumes:
    #  - /path/to/appdata/config:/config
    ports:
      - 2222:2222
    # restart: unless-stopped
